# Generated by Django 4.2.11 on 2024-03-07 10:57

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 180 characters or fewer. Letters, digits and @/./-/_ only.', max_length=180, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
